apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- name: fast-platform
  envs:
  - config.env
labels:
- pairs:
    app.kubernetes.io/name: hellnet-service
    app.kubernetes.io/instance: fast-platform
  includeSelectors: false
